spring.application.name=LearningPlatform

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:learningdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola de H2 (Para poder entrar a ver las tablas en el navegador y revisar)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate (Para que cree las tablas basadas en la clase @Entity Course)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Esto le dice a Spring que ejecute el script despues de crear las tablas
spring.jpa.defer-datasource-initialization=true

server.port=8082